### ISSUE TITLE
🐞 Bug – Debug logs not working with elm-land

### ISSUE THREAD

**Issue by Santhosh-KS** [elm-land/elm-land#185]
## Problem
When we use Debug.log in the elm-land projects, logs doesn't show up in the browser console.

Here is a simple repository I have created to illustrate the issue.
[Repo](https://github.com/Santhosh-KS/ElmLandDebugLogIssues/blob/5e1289a72d9579cdf10911002731906e20ba5214/src/Pages/Home_.elm#L45)

I'm trying to use the Debug.log to print out and see the flow of onclick events. Based on Elm  [youtube videos by Rayn](https://www.youtube.com/watch?v=cp3CEqo5VwU&list=PLuGpJqnV9DXq_ItwwUoJOGk_uCr72Yvzb&index=23&pp=iAQB).

On a normal application without elm-land Debug-log works fine. But not with eml-land. Not sure what additional configurations needs to be done to get it working. 

I could also see that the elm debugger is able to show the events clicked. But no logs show up in the terminal nor in the browser console. I could see the vite logs of connecting and connected messages, but when the events triggered by cliking the element, no logs are shown.

> What problem did you run into when using Elm Land?

## Your setup

OS: Linux Ubuntu: 24.04

```bash
# node -v
v21.1.0

# elm-land -v
🌈  Elm Land (v0.20.1) is currently installed.
```

**Comment by Santhosh-KS** [comment]
```bash
# node -v
v21.1.0

# elm-land -v

🌈  Elm Land (v0.20.1) is currently installed.

```

**Comment by dennistruemper** [comment]
Hi @Santhosh-KS. Have a look at the [Debug.log]( https://package.elm-lang.org/packages/elm/core/latest/Debug#log) function.

It takes 2 parameters, but you are just passing the String. Try something like this:

` Debug.log "Update called" model
`
instead of

` Debug.log "Update called"`

This change made it work:
![image](https://github.com/user-attachments/assets/8614cb4d-3800-44af-85ec-07b3fa02ff31)

**Comment by Santhosh-KS** [comment]
Thank you @dennistruemper . You are absolutely spot on! :) Will close this ticket.
