### ISSUE TITLE
🐞 Bug – Errors caused by Emacs lock and backup files 

### ISSUE THREAD

**Issue by schnef** [elm-land/elm-land#53]
Emacs creates lock and backup files which somehow cause errors:
```
frans@tp:~/pages-and-layouts$ elm-land server
Error: ENOENT: no such file or directory, open '/home/frans/pages-and-layouts/src/Pages/Home_..elm'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.readFromUserFolder (/usr/lib/node_modules/elm-land/src/files.js:150:20)
    at /usr/lib/node_modules/elm-land/src/effects.js:146:36
    at Array.map (<anonymous>)
    at generateElmFiles (/usr/lib/node_modules/elm-land/src/effects.js:145:39)
    at runServer (/usr/lib/node_modules/elm-land/src/effects.js:85:11)
    at async Object.run (/usr/lib/node_modules/elm-land/src/effects.js:394:22)
    at async main (/usr/lib/node_modules/elm-land/src/index.js:11:16) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/frans/pages-and-layouts/src/Pages/Home_..elm'
}
```
The lock file looks like `.#file.ext`. A backup file has the form `file.ext~`.
Is it possible to ignore these files under all conditions?
A work-around is to disable lock and backup files in Emacs with 
```
(setq create-lockfiles nil)
(setq make-backup-files nil)
```

**Comment by marciofrayze** [comment]
I'm not an emacs user anymore, but I think this is another workaround (for those that don't want to disable the backup files):

```
;; Put backups in a different directory
(setq backup-directory-alist `(("." . "~/emacs/.saves")))
```

**Comment by woochica** [comment]
For the context, this problem exists in the React/watchpack world too.
- [Development server errors due to emacs file lock](https://github.com/facebook/create-react-app/issues/9056)
- [ReactJS local server crashes after editing file in Emacs even without saving](https://stackoverflow.com/questions/62567370/reactjs-local-server-crashes-after-editing-file-in-emacs-even-without-saving)

I'm aware of two solutions:
- [Disable lockfiles in Emacs for the project only](https://stackoverflow.com/a/62571200/73603)
- Define a blocklist in Elm Land which files to ignore for watching

**Comment by petteraas** [comment]
I mostly use Intellij ( with the intellij-elm plugin ), and I do see the same problem everytime I save changes to a Pages file ( I tested changing a Layouts file, but that doesn't seem to cause any such issue ) . 

Adding a simple console.log inside of files.js readFromUserFolder I can see that there are temporary files with a extra `.` before the elm extension
