### ISSUE TITLE
Feature Request: Server Side Rendering

### ISSUE THREAD

**Issue by rametta** [elm-land/elm-land#56]
Elm land is looking really promising as a solid framework for building SPA's. These days though I can't imagine using something that doesn't support on-demand server side rendering of pages. Would love if that was added to Elm land with an API similar to [Remix](https://remix.run/) with their `loaders` and `actions`.

**Comment by ryannhg** [comment]
Hey @rametta 👋 

I'd love to hear more about your use case with server-side rendering!

There are other SSR-focused projects like [elm-pages](https://github.com/dillonkearns/elm-pages), but Elm Land's current focus is to provide clear guides and tooling for creating "web applications" rather than "websites". 

Generally, that means Elm Land isn't a great choice at the moment for use cases that might need SEO, control over `<meta>` tags, or the ability to pre-render HTML before the JavaScript on the page runs. 

---

Unlike many open source projects, our GitHub Issues space isn't for suggesting features for the framework. I use GitHub for tracking bugs / issues. 

That being said– I want to hear more about your experience with Remix, and what problems you're hoping SSR will solve for your web projects!

If you're interested, please swing by the [Elm Land Discord](https://join.elm.land) and drop your idea in the dedicated `#suggest-a-feature` channel. I check the Discord more frequently, and it's easier for me to track conversations there!

I'm closing this issue, and thank you for improving Elm Land! 🌈
